# 1. Array Creation & Inspection

In this section, we import `numpy` and create a 2D array of shape (4, 4) containing numbers from 1 to 16.
We then inspect its main attributes: `shape`, `dtype`, and `ndim`.

In [2]:
import numpy as np

arr_2d = np.arange(1,17).reshape(4,4)

print("---2D Array---")
print(arr_2d)
print("\nArray shape:", arr_2d.shape)
print("Data type:",arr_2d.dtype)
print("Number of Dimensions:",arr_2d.ndim)

---2D Array---
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

Array shape: (4, 4)
Data type: int64
Number of Dimensions: 2


# 2. Array Slicing & Indexing

Here, we demonstrate slicing multidimensional arrays:
- Extracting the **second column** (index 1 across all rows).
- Extracting the **last row** (index -1).
- Extracting a **2x2 sub-matrix** from the center.

In [3]:
# Extract the second column (all rows, index 1)
second_column = arr_2d[:,1]

#Extracting the last row (index -1)
last_row = arr_2d[-1, :]

## Extract a 2x2 sub-matrix from the center (rows 1-2, cols 1-2)
center_subMatrix = arr_2d[1:3 , 1:3]

print("Second column:" , second_column)
print("Last row:", last_row)
print("\nCenter sub-matrix:\n",  center_subMatrix)

Second column: [ 2  6 10 14]
Last row: [13 14 15 16]

Center sub-matrix:
 [[ 6  7]
 [10 11]]


# 3. Boolean Masking & Vectorized Operations

NumPy allows fast element-wise operations and conditional filtering without explicit loops:
- We compute statistical metrics (`mean`, `sum`, `std`).
- We apply a **Boolean Mask** to filter elements strictly greater than the mean.

In [9]:
#mean value
mean_value = arr_2d.mean()

#sum value
sum_value = arr_2d.sum()

#std value
std_value = arr_2d.std()

print(f"Mean: {mean_value}, Sum: {sum_value}, Std Dev: {std_value:.2f}")

# Create boolean mask for values > mean
mask = arr_2d > mean_value
filtered_values = arr_2d[mask]
print("\nBoolean mask (true where value > mean):\n", mask)
print("\nFilterd Values (greater than mean):\n", filtered_values)

Mean: 8.5, Sum: 136, Std Dev: 4.61

Boolean mask (true where value > mean):
 [[False False False False]
 [False False False False]
 [ True  True  True  True]
 [ True  True  True  True]]

Filterd Values (greater than mean):
 [ 9 10 11 12 13 14 15 16]


# 4. NumPy Broadcasting

Broadcasting enables arithmetic operations between arrays of different shapes:
- We add a 1D row vector `[10, 20, 30, 40]` to our 2D `(4, 4)` array.

In [11]:
# Define a 1D array with shape (4,)
row_vector = np.array([10, 20, 30, 40])

# Perform broadcasting addition
broadcasted_result = arr_2d + row_vector

print("Original Array:\n", arr_2d)
print("\n1D Row Vector to Add:\n", row_vector)
print("\nResult after Broadcasting:\n", broadcasted_result)

Original Array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

1D Row Vector to Add:
 [10 20 30 40]

Result after Broadcasting:
 [[11 22 33 44]
 [15 26 37 48]
 [19 30 41 52]
 [23 34 45 56]]
